const VendreDofusKamas = [
  {
    serveur: "Boune",
    prixEur: 7.181,
    prixUsd: 7.845,
    prixDh: 84.73,
    etat: true,
  },
  {
    serveur: "Crail",
    prixEur: 0.945,
    prixUsd: 1.032,
    prixDh: 11.15,
    etat: true,
  },
  {
    serveur: "Draconiros",
    prixUsd: 1.101,
    prixEur: 1.008,
    prixDh: 11.89,
    etat: true,
  },
  {
    serveur: "Eratz",
    prixEur: 0.159,
    prixUsd: 0.174,
    prixDh: 1.88,
    etat: true,
  },
  {
    serveur: "Galgarion",
    prixEur: 1.166,
    prixUsd: 1.274,
    prixDh: 13.76,
    etat: true,
  },
  {
    serveur: "HellMina",
    prixEur: 0.593,
    prixUsd: 0.648,
    prixDh: 7,
    etat: true,
  },
  {
    serveur: "Henual",
    prixEur: 0.593,
    prixUsd: 0.648,
    prixDh: 7,
    etat: true,
  },
  {
    serveur: "Imagiro",
    prixEur: 0.593,
    prixUsd: 0.648,
    prixDh: 7,
    etat: true,
  },
  {
    serveur: "Ombre(Shadow)",
    prixEur: 0.508,
    prixUsd: 0.556,
    prixDh: 6,
    etat: true,
  },
  {
    serveur: "Orukam",
    prixEur: 0.607,
    prixUsd: 0.663,
    prixDh: 7.16,
    etat: true,
  },
  {
    serveur: "TalKasha",
    prixEur: 0.593,
    prixUsd: 0.648,
    prixDh: 7,
    etat: false,
  },
  {
    serveur: "Tylezia",
    prixEur: 0.581,
    prixUsd: 0.634,
    prixDh: 6.85,
    etat: false,
  },
];

const VendreDofusTouchKamas = [
  {
    serveur: "Dodge",
    prixDh: 16,
    prixEur: 1.356,
    prixUsd: 1.481,
    etat: false,
  },
  {
    serveur: "Grandapan",
    prixDh: 15,
    prixEur: 1.271,
    prixUsd: 1.389,
    etat: true,
  },
  {
    serveur: "Herdegrize",
    prixDh: 38.36,
    prixEur: 3.251,
    prixUsd: 3.552,
    etat: false,
  },
  {
    serveur: "Oshimo",
    prixDh: 38,
    prixEur: 3.22,
    prixUsd: 3.519,
    etat: false,
  },
  {
    serveur: "Terra Cogita",
    prixDh: 40,
    prixEur: 3.39,
    prixUsd: 3.704,
    etat: false,
  },
];

const AcheterDofusKamas = [
  {
    serveur: "Boune",
    prixDh: 118.62,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Crail",
    prixDh: 15.61,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Draconiros",
    prixDh: 16.65,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Eratz",
    prixDh: 2.63,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Galgarion",
    prixDh: 19.26,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "HellMina",
    prixDh: 9.8,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Henual",
    prixDh: 9.8,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Imagiro",
    prixDh: 9.8,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Ombre(Shadow)",
    prixDh: 8.4,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Orukam",
    prixDh: 10.02,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "TalKasha",
    prixDh: 9.8,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Tylezia",
    prixDh: 9.59,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
];
const AcheterDofusTouchKamas = [
  {
    serveur: "Dodge",
    prixDh: 22.4,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Grandapan",
    prixDh: 21.0,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Herdegrize",
    prixDh: 53.7,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Oshimo",
    prixDh: 53.2,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
  {
    serveur: "Terra Cogita",
    prixDh: 56.0,
    prixEur: 0,
    prixUsd: 0,
    etat: true,
  },
];

module.exports = {
  VendreDofusKamas,
  VendreDofusTouchKamas,
  AcheterDofusKamas,
  AcheterDofusTouchKamas,
};
